@url = http://localhost:8080
@authorization = Bearer {{auth.response.body.token}}

###login 
# @name auth
POST {{url}}/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "admin"
}

### Create establishment
POST {{url}}/establishment HTTP/1.1
Content-Type: application/json
Authorization: {{authorization}}

{
  "name": "Lilla Park",
  "ein": "50322233211",
  "address": "778 Breitenberg Key",
  "phone": "400-650-7636",
  "parkingSpacesCar": 246,
  "parkingSpacesMotorcycle": 908
}

### Create vehicle
POST {{url}}/vehicle HTTP/1.1
Content-Type: application/json
Authorization: {{authorization}}

{
  "brand": "Toyota",
  "model": "Corolla",
  "color": "Blue",
  "plate": "ABC-1234",
  "type": "CAR"
}

### park vehicle 
PUT {{url}}/establishment/1/vehicle HTTP/1.1
Content-Type: application/json
Authorization: {{authorization}}

{
  "vehicleId": 1
}

### unpark vehicle
DELETE {{url}}/establishment/22/vehicle HTTP/1.1
Content-Type: application/json
Authorization: {{authorization}}

{
  "vehicleId": 3
}

### Get establishment
GET {{url}}/establishment HTTP/1.1
Authorization: {{authorization}}

### Get vehicle
GET {{url}}/vehicle HTTP/1.1
Authorization: {{authorization}}

### get users
GET {{url}}/users HTTP/1.1
Authorization: {{authorization}}