services:
  db:
    image: bitnami/postgresql:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: parking
    ports:
      - "5444:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
